export const types = {
  GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
  GET_SINGLE_COUNTRY: "GET_SINGLE_COUNTRY",
  FILTER_BY_CONTINENT: "FILTER_BY_CONTINENT",
  FILTER_BY_ALPHABETICAL_ORDER: "ALPHABETICAL_ORDER",
  FILTER_BY_POPULATION_ORDER: "POPULATION_ORDER",
  FILTER_BY_ACTIVITIES: "FILTER_ACTIVITIES",
  GET_COUNTRY: "GET_COUNTRY",
  RESET_FILTERS: "RESET_FILTERS",
  GET_ERROR: "GET_ERROR",
  POST_ACTIONS: "POST_ACTIONS",
  CLEAN_COUNTRY: "CLEAN_COUNTRY",
  GET_ACTIVITIES: "GET_ACTIVITIES",
}